version: '3'
services:
  prismaagent:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "8866:8866"
    environment:
      PRISMA_CONFIG: |
        port: 8866
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: records
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true
            connectionLimit: 5
  records:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - records:/var/lib/mysql
volumes:
  records:
